import type { Rule } from '@unocss/core';
import { mixBlendModes } from './effects'
import  { paddings, margins } from './spacing';

// this should be all rewritten to be defined as files in this project
import {
  alignments,
  appearance,
  appearances,
  aspectRatio,
  bgColors,
  borders,
  boxShadows,
  boxSizing,
  contents,
  cursors,
  displays,
  flex,
  floats,
  fontSmoothings,
  fontStyles,
  fonts,
  gaps,
  grids,
  insets,
  justifies,
  cssVariables as miniCssVariables,
  opacity,
  orders,
  outline,
  overflows,
  placements,
  pointerEvents,
  positions,
  questionMark,
  resizes,
  rings,
  sizes,
  svgUtilities,
  tabSizes,
  textAligns,
  textColors,
  textDecorations,
  textIndents,
  textOverflows,
  textShadows,
  textStrokes,
  transforms,
  transitions,
  userSelects,
  verticalAligns,
  whitespaces,
  willChange,
  breaks as wordBreaks,
  zIndexes,
} from '@unocss/preset-mini/rules'

export const rules: Rule[] = [
  miniCssVariables,
  // cssVariables,
  // container,
  // screenReadersAccess,
  pointerEvents,
  appearances,
  positions,
  insets,
  // lineClamps,
  // isolations,
  zIndexes,
  orders,
  grids,
  floats,
  margins,
  boxSizing,
  displays,
  aspectRatio,
  sizes,
  flex,
  // tables,
  transforms,
  // animations,
  cursors,
  // touchActions,
  userSelects,
  resizes,
  // scrolls,
  // listStyle,
  appearance,
  // columns,
  placements,
  alignments,
  justifies,
  gaps,
  // spaces,
  // divides,
  overflows,
  // overscrolls,
  // scrollBehaviors,
  textOverflows,
  whitespaces,
  wordBreaks,
  borders,
  bgColors,
  // boxDecorationBreaks,
  // backgroundStyles,
  svgUtilities,
  // objectPositions,
  paddings,
  textAligns,
  textIndents,
  verticalAligns,
  fonts,
  // textTransforms,
  fontStyles,
  // fontVariantNumeric,
  textColors,
  textDecorations,
  fontSmoothings,
  tabSizes,
  textStrokes,
  textShadows,
  // hyphens,
  // writingModes,
  // writingOrientations,
  // caretColors,
  // caretOpacity,
  // accentColors,
  // accentOpacity,
  opacity,
  mixBlendModes,
  boxShadows,
  outline,
  rings,
  // imageRenderings,
  // filters,
  transitions,
  willChange,
  contents,

  // should be the last
  questionMark,
].flat(1)