export const variantOrder = [
  'hover',
  'focus',
  'active',
  'visited',
  'link',
  'target',
  'focus-visible',
  'focus-within',
  'checked',
  'not-checked',
  'default',
  'disabled',
  'enabled',
  'indeterminate',
  'invalid',
  'valid',
  'optional',
  'required',
  'placeholder-shown',
  'read-only',
  'read-write',
  'not-disabled',
  'first-of-type',
  'not-first-of-type',
  'last-of-type',
  'not-last-of-type',
  'first',
  'last',
  'not-first',
  'not-last',
  'only-child',
  'not-only-child',
  'only-of-type',
  'not-only-of-type',
  'even',
  'odd',
  'even-of-type',
  'odd-of-type',
  'root',
  'empty',
  'before',
  'after',
  'first-letter',
  'first-line',
  'selection',
  'svg',
  'all',
  'children',
  'siblings',
  'sibling',
  'ltr',
  'rtl',
  'group-hover',
  'group-focus',
  'group-active',
  'group-visited',
  'motion-safe',
  'motion-reduce',
];

export enum layerOrder {
  base,
  components,
  shortcuts,
  utilities,
}

export enum pluginOrder {
  container,
  space,
  divideWidth,
  divideColor,
  divideStyle,
  divideOpacity,
  accessibility,
  appearance,
  backgroundAttachment,
  backgroundClip,
  backgroundColor,
  backgroundImage,
  gradientColorStops,
  backgroundOpacity,
  backgroundPosition,
  backgroundRepeat,
  backgroundSize,
  backgroundOrigin,
  borderCollapse,
  borderColor,
  borderOpacity,
  borderRadius,
  borderStyle,
  borderWidth,
  boxDecorationBreak,
  boxSizing,
  cursor,
  captionSide,
  emptyCells,
  display,
  flexDirection,
  flexWrap,
  placeItems,
  placeContent,
  placeSelf,
  alignItems,
  alignContent,
  alignSelf,
  justifyItems,
  justifyContent,
  justifySelf,
  flex,
  flexGrow,
  flexShrink,
  order,
  float,
  clear,
  fontFamily,
  fontWeight,
  height,
  fontSize,
  lineHeight,
  listStylePosition,
  listStyleType,
  margin,
  maxHeight,
  maxWidth,
  minHeight,
  minWidth,
  objectFit,
  objectPosition,
  opacity,
  outline,
  overflow,
  overscrollBehavior,
  padding,
  placeholderColor,
  placeholderOpacity,
  caretColor,
  caretOpacity,
  tabSize,
  pointerEvents,
  position,
  inset,
  resize,
  boxShadow,
  boxShadowColor,
  ringWidth,
  ringOffsetColor,
  ringOffsetWidth,
  ringColor,
  ringOpacity,
  fill,
  stroke,
  strokeWidth,
  strokeDashArray,
  strokeDashOffset,
  tableLayout,
  textAlign,
  textColor,
  textOpacity,
  textOverflow,
  textShadow,
  fontStyle,
  textTransform,
  textDecorationStyle,
  textDecorationLength,
  textDecorationColor,
  textDecorationOpacity,
  textDecorationOffset,
  textDecoration,
  textIndent,
  textStrokeColor,
  textStrokeWidth,
  fontSmoothing,
  fontVariantNumeric,
  letterSpacing,
  userSelect,
  verticalAlign,
  visibility,
  backfaceVisibility,
  whitespace,
  wordBreak,
  writingMode,
  hyphens,
  width,
  zIndex,
  isolation,
  gap,
  gridAutoFlow,
  gridTemplateColumns,
  gridAutoColumns,
  gridColumn,
  gridColumnStart,
  gridColumnEnd,
  gridTemplateRows,
  gridAutoRows,
  gridRow,
  gridRowStart,
  gridRowEnd,
  transform,
  transformOrigin,
  scale,
  rotate,
  translate,
  skew,
  perspective,
  perspectiveOrigin,
  transitionProperty,
  transitionTimingFunction,
  transitionDuration,
  transitionDelay,
  keyframes,
  animation,
  imageRendering,
  mixBlendMode,
  backgroundBlendMode,
  filter,
  blur,
  brightness,
  contrast,
  dropShadow,
  grayscale,
  hueRotate,
  invert,
  saturate,
  sepia,
  backdropFilter,
  backdropBlur,
  backdropBrightness,
  backdropContrast,
  backdropGrayscale,
  backdropHueRotate,
  backdropInvert,
  backdropOpacity,
  backdropSaturate,
  backdropSepia,
}

export const keyOrder: { [key: string]: number } = {
  container: 201,
  space: 202,
  divide: 203,
  bg: 204,
  from: 205,
  via: 206,
  to: 207,
  border: 208,
  rounded: 209,
  cursor: 210,
  flex: 211,
  order: 212,
  font: 213,
  h: 214,
  list: 215,
  m: 216,
  my: 217,
  mx: 218,
  mt: 219,
  mr: 220,
  mb: 221,
  ml: 222,
  min: 223,
  max: 224,
  object: 225,
  opacity: 226,
  outline: 227,
  p: 228,
  py: 229,
  px: 230,
  pt: 231,
  pr: 232,
  pb: 233,
  pl: 234,
  placeholder: 235,
  inset: 236,
  top: 237,
  right: 238,
  bottom: 239,
  left: 240,
  shadow: 241,
  ring: 242,
  fill: 243,
  stroke: 244,
  text: 245,
  leading: 246,
  tracking: 247,
  w: 248,
  z: 249,
  gap: 250,
  auto: 251,
  grid: 252,
  col: 253,
  row: 254,
  transform: 255,
  origin: 256,
  scale: 257,
  rotate: 258,
  translate: 259,
  skew: 260,
  transition: 261,
  ease: 262,
  duration: 263,
  delay: 264,
  animate: 265,
};
