export enum variantOrder {
  'first',
  'last',
  'odd',
  'even',
  'visited',
  'checked',
  'group-hover',
  'group-focus',
  'focus-within',
  'hover',
  'focus',
  'focus-visible',
  'active',
  'disabled',
}

// export enum utilityOrder {
//   "preflight",
//   "container",
//   "space",
//   "divideWidth",
//   "divideColor",
//   "divideStyle",
//   "divideOpacity",
//   "accessibility",
//   "appearance",
//   "backgroundAttachment",
//   "backgroundClip",
//   "backgroundColor",
//   "backgroundImage",
//   "gradientColorStops",
//   "backgroundOpacity",
//   "backgroundPosition",
//   "backgroundRepeat",
//   "backgroundSize",
//   "borderCollapse",
//   "borderColor",
//   "borderOpacity",
//   "borderRadius",
//   "borderStyle",
//   "borderWidth",
//   "boxSizing",
//   "cursor",
//   "display",
//   "flexDirection",
//   "flexWrap",
//   "placeItems",
//   "placeContent",
//   "placeSelf",
//   "alignItems",
//   "alignContent",
//   "alignSelf",
//   "justifyItems",
//   "justifyContent",
//   "justifySelf",
//   "flex",
//   "flexGrow",
//   "flexShrink",
//   "order",
//   "float",
//   "clear",
//   "fontFamily",
//   "fontWeight",
//   "height",
//   "fontSize",
//   "lineHeight",
//   "listStylePosition",
//   "listStyleType",
//   "margin",
//   "maxHeight",
//   "maxWidth",
//   "minHeight",
//   "minWidth",
//   "objectFit",
//   "objectPosition",
//   "opacity",
//   "outline",
//   "overflow",
//   "overscrollBehavior",
//   "padding",
//   "placeholderColor",
//   "placeholderOpacity",
//   "pointerEvents",
//   "position",
//   "inset",
//   "resize",
//   "boxShadow",
//   "ringWidth",
//   "ringOffsetColor",
//   "ringOffsetWidth",
//   "ringColor",
//   "ringOpacity",
//   "fill",
//   "stroke",
//   "strokeWidth",
//   "tableLayout",
//   "textAlign",
//   "textColor",
//   "textOpacity",
//   "textOverflow",
//   "fontStyle",
//   "textTransform",
//   "textDecoration",
//   "fontSmoothing",
//   "fontVariantNumeric",
//   "letterSpacing",
//   "userSelect",
//   "verticalAlign",
//   "visibility",
//   "whitespace",
//   "wordBreak",
//   "width",
//   "zIndex",
//   "gap",
//   "gridAutoFlow",
//   "gridTemplateColumns",
//   "gridAutoColumns",
//   "gridColumn",
//   "gridColumnStart",
//   "gridColumnEnd",
//   "gridTemplateRows",
//   "gridAutoRows",
//   "gridRow",
//   "gridRowStart",
//   "gridRowEnd",
//   "transform",
//   "transformOrigin",
//   "scale",
//   "rotate",
//   "translate",
//   "skew",
//   "transitionProperty",
//   "transitionTimingFunction",
//   "transitionDuration",
//   "transitionDelay",
//   "animation",
// }

export const keyOrder: { [key: string]: number } = {
  container: 201,
  space: 202,
  divide: 203,
  bg: 204,
  from: 205,
  via: 206,
  to: 207,
  border: 208,
  rounded: 209,
  cursor: 210,
  flex: 211,
  order: 212,
  font: 213,
  h: 214,
  list: 215,
  m: 216,
  my: 217,
  mx: 218,
  mt: 219,
  mr: 220,
  mb: 221,
  ml: 222,
  min: 223,
  max: 224,
  object: 225,
  opacity: 226,
  outline: 227,
  p: 228,
  py: 229,
  px: 230,
  pt: 231,
  pr: 232,
  pb: 233,
  pl: 234,
  placeholder: 235,
  inset: 236,
  top: 237,
  right: 238,
  bottom: 239,
  left: 240,
  shadow: 241,
  ring: 242,
  fill: 243,
  stroke: 244,
  text: 245,
  leading: 246,
  tracking: 247,
  w: 248,
  z: 249,
  gap: 250,
  auto: 251,
  grid: 252,
  col: 253,
  row: 254,
  transform: 255,
  origin: 256,
  scale: 257,
  rotate: 258,
  translate: 259,
  skew: 260,
  transition: 261,
  ease: 262,
  duration: 263,
  delay: 264,
  animate: 265,
};
